### ISSUE TITLE
Unable to create a pool - Incoming request (v18_2_2) has field (delete_server_on_dns_refresh) introduced in later versions(v18_2_3)

### ISSUE THREAD

**Issue by kenerwin88** [terraform-providers/terraform-provider-avi#14]
Hello,

I am unable to create a pool (using the avi_pool resource).  I've tested using the latest version of the provider, with both Terraform v0.11.14 and v0.12.10, using AVI provider v0.2.0.

resource "avi_pool" "testpool" {
  name                                = "pool-42"
  health_monitor_refs                 = ["${avi_healthmonitor.openlane_hm_http.id}"]
  tenant_ref                          = "${avi_tenant.openlane.id}"
  cloud_ref                           = "cloud-9b31d623-181b-49c3-b2e1-bb5d87257150"
  application_persistence_profile_ref = "System-Persistence-Client-IP"

  servers {
    ip = {
      type = "V4"
      addr = "10.90.64.66"
    }

    port = 8080
  }
}

Error I'm seeing:

1 error occurred:
	* avi_pool.testpool: 1 error occurred:
	* avi_pool.testpool: Encountered an error on POST request to URL https://controller-nonprod.karops.io/api/pool: HTTP code: 400; error from Avi: map[error:Incoming request (v18_2_2) has field (delete_server_on_dns_refresh) introduced in later versions(v18_2_3).]

**Comment by bg2132332** [comment]
Same problem.

**Comment by grastogi23** [comment]
> Hello,
> 
> I am unable to create a pool (using the avi_pool resource). I've tested using the latest version of the provider, with both Terraform v0.11.14 and v0.12.10, using AVI provider v0.2.0.
> 
> resource "avi_pool" "testpool" {
> name = "pool-42"
> health_monitor_refs = ["${avi_healthmonitor.openlane_hm_http.id}"]
> tenant_ref = "${avi_tenant.openlane.id}"
> cloud_ref = "cloud-9b31d623-181b-49c3-b2e1-bb5d87257150"
> application_persistence_profile_ref = "System-Persistence-Client-IP"
[GR] This is invalid syntax. You need to use a datasource to fetch the id of the application_persistence_profile_ref. Please try again and let us know.

> 
> servers {
> ip = {
> type = "V4"
> addr = "10.90.64.66"
> }
> 
> ```
> port = 8080
> ```
> 
> }
> }
> 
> Error I'm seeing:
> 
> 1 error occurred:
> * avi_pool.testpool: 1 error occurred:
> * avi_pool.testpool: Encountered an error on POST request to URL https://controller-nonprod.karops.io/api/pool: HTTP code: 400; error from Avi: map[error:Incoming request (v18_2_2) has field (delete_server_on_dns_refresh) introduced in later versions(v18_2_3).]

**Comment by bg2132332** [comment]
Gaurav, thank you for your reply.  Your suggestion didn't work for me -- TF still complained about "delete_server_on_dns_refresh" setting (as above) which isn't in avi_pool resource spec.  

error from Avi: map[error:Incoming request (v18_2_2) has field (delete_server_on_dns_refresh) introduced in later versions(v18_2_3).]

As a guess, I tried adding this value to avi_pool and set it to "false" and this worked for me:

resource "avi_pool" "mypool" {
name = "mypool"
...
delete_server_on_dns_refresh = "1" 
...
}

**Comment by chaitanyaavi** [comment]
@bg2132332 
This is happening because you are not providing the proper version of the controller to the provider
the field delete_server_on_dns_refresh is introduced in later versions of the 18.2.3 controller and the default version of the controller in the terraform provider is 18.2.2 so you need to pass the appropriate version of the controller to the provider.
You can pass the controller version by setting  avi_version in the provider

**Comment by bartsqueezy** [comment]
I was experiencing the same issue after upgrading to the 18.2.6 release.  @chaitanyaavi's recommendation solved the issue for me.  However, I'm thinking this should be listed in the main README/TF docs as it seems like a common issue that could come up again.

**Comment by grastogi23** [comment]
18.2.5 and 18.2.6 would be our LTS. There are very few customers on the 18.2.2. Closing the issue.
