### ISSUE TITLE
How to configure  health monitor properly?

### ISSUE THREAD

**Issue by bg2132332** [terraform-providers/terraform-provider-avi#15]
I'm interested in TCP, HTTP, HTTPS and UDP health monitors.  avi_healthmonitor resource has tcp_monitor, udp_monitor, http_monitor and https_monitor settings.  How are these values set?

**Comment by chaitanyaavi** [comment]
@bg2132332 Please find examples at below link
https://github.com/avinetworks/devops/tree/master/terraform/avi_config/healthmonitors
