### ISSUE TITLE
Unable to retrieve IP-address of avi_virtualservice

### ISSUE THREAD

**Issue by RomanKrasavtsev** [terraform-providers/terraform-provider-avi#2]
Hi team, 

I would like to create a DNS entry that refers to avi_virtualservice with auto allocated IP-address.
Would be very grateful if you could provide some advice how to retrieve IP-address of avi_virtualservice.

I am using OpenStack, but I suppose it should be similar for all clouds so here you could find the sample:
https://github.com/terraform-providers/terraform-provider-avi/blob/master/examples/aws/avi_app/avi_config.tf#L395

Unfortunately, output doesn't show the IP-address, so I can't assign it. 
```
avi_virtualservice_vip = [
  {
    "auto_allocate_floating_ip" = false
    "auto_allocate_ip" = true
    "auto_allocate_ip_type" = "V4_ONLY"
    "availability_zone" = ""
    "avi_allocated_fip" = false
    "avi_allocated_vip" = true
    "discovered_networks" = []
    "enabled" = true
    "floating_ip" = []
    "floating_ip6" = []
    "floating_subnet6_uuid" = ""
    "floating_subnet_uuid" = ""
    "ip6_address" = []
    "ip_address" = []
    "ipam_network_subnet" = []
    "network_ref" = ""
    "placement_networks" = []
    "port_uuid" = ""
    "subnet" = [
      {
        "ip_addr" = [
          {
            "addr" = "SUBNET_WAS_HERE"
            "type" = "V4"
          },
        ]
        "mask" = 26
      },
    ]
    "subnet6" = []
    "subnet6_uuid" = ""
    "subnet_uuid" = "SUBNET_UUID_WAS_HERE"
    "vip_id" = "0"
  },
]
```

Thank you in advance for your help.

**Comment by abooitt** [comment]
Supporting my colleague here.
This problem is similar to https://github.com/avinetworks/terraform-provider-avi-backup/pull/115 which was merged at some point. It does not work for us now, while it does work for us, when the change is applied on top of master branch at https://github.com/avinetworks/terraform-provider-avi-backup/commit/fc6b37db7c3879e333c2b698eab9d680c5dd4a57

For some reason the `ip_address` attribute of the avi_virtualservice_vip is an empty list.

**Comment by grastogi23** [comment]
@abooitt can you please try with the latest terraform code. This has been fixed as AV-66748 pull request https://github.com/terraform-providers/terraform-provider-avi/pull/6

**Comment by abooitt** [comment]
@grastogi23 will try

**Comment by RomanKrasavtsev** [comment]
@grastogi23 thank you! 

I confirm that the issue was fixed:
```
$ terraform console
> avi_virtualservice.test.vip.0.ip_address
[
  {
    "addr" = "1.2.3.4"
    "type" = "V4"
  },
]
```
