### ISSUE TITLE
aws example aws_iam_instance_profile data source

### ISSUE THREAD

**Issue by tobmat** [terraform-providers/terraform-provider-avi#5]
I'm not sure if I'm missing something but there is a data source for aws_iam_instance_profile here:
https://github.com/terraform-providers/terraform-provider-avi/blob/master/examples/aws/aws_resources/aws.tf

I don't see where that data resource for aws_iam_instance_profile is being created in this example?

**Comment by grastogi23** [comment]
The IAM profile used here is based on a datasource 
data "aws_iam_instance_profile" "avi_controller_iam" {
  name = "AviControllerRole"
}
